### ISSUE TITLE
Running 2 models?

### ISSUE THREAD

**Issue by AlistairMRoss** [Seeed-Studio/Seeed_Arduino_SSCMA#16]
- Is it possible to run 2 models
- For instance in the application of using the first model to detect and then passing the image to the second model to be analyzed?

**Comment by LynnL4** [comment]
Hi，The model pipeline is not currently supported.

**Comment by LynnL4** [comment]
Hi, We plan to support multiple models in subsequent releases, so stay tuned! https://github.com/Seeed-Studio/SSCMA-Micro

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
