### ISSUE TITLE
Can't building library in Arduino IDE -  #include <vector>

### ISSUE THREAD

**Issue by markncooper** [Seeed-Studio/Seeed_Arduino_SSCMA#20]
I'm getting the following error when trying to compile the following simple sample:

```
#include <Seeed_Arduino_SSCMA.h>

SSCMA AI;

void setup()
{
    AI.begin();
    Serial.begin(9600);
}

void loop()
{
}

```

Any advice?

/usr/local/bin/arduino-cli compile --fqbn arduino:avr:uno --build-cache-path /tmp --output-dir /tmp/688813468/build --build-path /tmp/arduino-build-2C321F43817DAC728B7EFB3A5A80A84F  /tmp/688813468/inference

In file included from /tmp/688813468/inference/inference.ino:1:0:
/home/builder/Arduino/libraries/seeed_arduino_sscma_1_0_0/src/Seeed_Arduino_SSCMA.h:51:10: fatal error: vector: No such file or directory
 #include <vector>
          ^~~~~~~~
compilation terminated.

Error during build: exit status 1

**Comment by LynnL4** [comment]
#21
