### ISSUE TITLE
Is it possible to retrieve the last image?

### ISSUE THREAD

**Issue by AlistairMRoss** [Seeed-Studio/Seeed_Arduino_SSCMA#7]

**Comment by LynnL4** [comment]
Hi,
If you enable the reply of image, you can get the image, it is recommended to get the image through the uart interface, if you want to get the image
https://github.com/Seeed-Studio/Seeed_Arduino_SSCMA/blob/e20575075904e16220d3694a91b553e6b0711028/examples/inference_uart/inference_uart.ino#L23
https://github.com/Seeed-Studio/Seeed_Arduino_SSCMA/blob/e20575075904e16220d3694a91b553e6b0711028/examples/inference_uart/inference_uart.ino#L99

**Comment by AlistairMRoss** [comment]
Thank you so much
